WebShop/GearShop/Areas/Admin/Controllers/CategoryController.cs
using Application.Common.ExtensionMethods;
using AspNetCoreHero.ToastNotification.Abstractions;
using Domain.Entities;
using GearShopWeb.Areas.Admin.Controllers;
using Infrastructure.Interface.IRepository;
using Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace ShoppingWeb.Areas.Admin.Controllers;

[Area("Admin")]
public class CategoryController : BaseController
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ApplicationDbContext _db;
    public INotyfService _notyfService { get; }
    public CategoryController(IUnitOfWork unitOfWork, INotyfService notyfService, ApplicationDbContext db)
    {
        _unitOfWork = unitOfWork;
        _notyfService = notyfService;
        _db = db;
    }
    public async Task<IActionResult> Index(int? pageNumber)
    {
        var paginatedList = await _db.Categories.PaginatedListAsync(pageNumber ?? 1, 4);
        return View(paginatedList);
    }

    public async Task<IActionResult> CreateAndUpdate(int? id)
    {
        if (id == null || id == 0)
        {
            Category c = new Category();
            return View(c);
        }
        else
        {
            Category c = await _unitOfWork.Category.Get(u => u.Id == id);
            return View(c);
        }
    }

    [HttpPost]
    public async Task<IActionResult> CreateAndUpdate(Category obj)
    {

        if (ModelState.IsValid)
        {
            //Create new
            if (obj.Id == 0)
            {
                await _unitOfWork.Category.Add(obj);
                _notyfService.Success("Category Added Successfully");
            }
            else
            {
                _unitOfWork.Category.Update(obj);
                _notyfService.Success("Category Updated Successfully");
            }
            await _unitOfWork.Save();

            return RedirectToAction("Index");
        }
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Delete(int? id)
    {
        Category? category = await _unitOfWork.Category.Get(x => x.Id == id);
        if (id == null || id == 0)
        {
            return NotFound();
        }
        await _unitOfWork.Category.Remove(category);
        await _unitOfWork.Save();
        _notyfService.Success("Deleted!");
        return RedirectToAction("Index");
    }



}

WebShop/GearShop/Areas/Admin/Controllers/ProductController.cs
using Application.Common.ExtensionMethods;
using AspNetCoreHero.ToastNotification.Abstractions;
using Domain.Entities;
using GearShopWeb.Areas.Admin.Controllers;
using Infrastructure.Interface.IRepository;
using Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models.ViewModels;

namespace GearShop.Areas.Admin.Controllers;

[Area("Admin")]
public class ProductController : BaseController
{
    #region Readonlys

    private readonly IUnitOfWork _unitOfWork;
    private readonly ApplicationDbContext _db;
    private readonly IWebHostEnvironment _webHostEnvironment;

    #endregion

    public INotyfService _notyfService { get; }

    #region Constructor

    public ProductController(IUnitOfWork unitOfWork,
        IWebHostEnvironment webHostEnvironment,
        INotyfService notyfService,
        ApplicationDbContext db)
    {
        _unitOfWork = unitOfWork;
        _webHostEnvironment = webHostEnvironment;
        _notyfService = notyfService;
        _db = db;
    }

    #endregion

    public async Task<IActionResult> Index(int? pageNumber)
    {
        var productList = await _db.Products.Include(x => x.Category)
                                            .PaginatedListAsync(pageNumber ?? 1, 4);
        return View(productList);
    }
    public async Task<IActionResult> CreateAndUpdate(int? id)
    {
        ProductVM productVM = new()
        {
            CategoryList = await _db.Categories.AsNoTracking()
            .Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            }).ToListAsync(),
            product = new Product()
        };
        if (id == null || id == 0)
        {
            // create 
            return View(productVM);
        }
        else
        {
            //update
            productVM.product = await _unitOfWork.Product.Get(u => u.Id == id);
            return View(productVM);
        }
    }
    [HttpPost]
    public async Task<IActionResult> CreateAndUpdate(ProductVM productVM, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            String wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productPath = Path.Combine(wwwRootPath, @"images\product");
                if (!string.IsNullOrEmpty(productVM.product.ImgUrl))
                {
                    //Delete old image
                    var oldImage = Path.Combine(wwwRootPath, productVM.product.ImgUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImage))
                    {
                        System.IO.File.Delete(oldImage);
                    }
                }
                using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
                productVM.product.ImgUrl = @"\images\product\" + fileName;
                //productVM.Product.ImgUrl = fileName;
            }

            if (productVM.product.Id == 0)
            {
                await _unitOfWork.Product.Add(productVM.product);
                _notyfService.Success("Product Added Successfully");
            }
            else
            {
                await _unitOfWork.Product.Update(productVM.product);
                _notyfService.Success("Product Updated Successfully");
            }

            await _unitOfWork.Save();
            return RedirectToAction("Index");
        }
        else
        {
            productVM.CategoryList = _db.Categories.Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View();
        }
    }

    [HttpDelete]
    public async Task<IActionResult> Delete(int? id)
    {
        Product? product = await _unitOfWork.Product.Get(x => x.Id == id);
        if (id == null || id == 0)
        {
            return NotFound();
        }
        await _unitOfWork.Product.Remove(product);
        await _unitOfWork.Save();
        _notyfService.Success("Deleted!");
        return RedirectToAction("Index");
    }

}

WebShop/GearShop/Areas/Admin/Controllers/UserController.cs
using Application.Common.ExtensionMethods;
using AspNetCoreHero.ToastNotification.Abstractions;
using GearShopWeb.Areas.Admin.Controllers;
using Infrastructure.Interface.IRepository;
using Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GearShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : BaseController
    {
        #region DI
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _db;
        public INotyfService _notyfService { get; }
        public UserController(IUnitOfWork unitOfWork,
            INotyfService notyfService,
            ApplicationDbContext db)
        {
            _unitOfWork = unitOfWork;
            _notyfService = notyfService;
            _db = db;
        }
        #endregion
        // GET: UserController1
        public async Task<ActionResult> Index(int? pageNumber)
        {
            var users = await _db.Users.Include(x => x.Role)
                                       .Where(x => x.Role.IsAdmin == false)
                                       .PaginatedListAsync(pageNumber ?? 1, 4);
            return View(users);
        }

        // GET: UserController1/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserController1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController1/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebShop/GearShop/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/Admin_assets/img/favicon.png" rel="icon">
    <link href="~/Admin_assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <partial name="_Css"></partial>

</head>

<body>

    <!-- ======= Header ======= -->
    <partial name="_HeaderPartial"></partial>
    <!-- ======= Sidebar ======= -->
    <partial name="_LeftSidebarPartial"></partial>

    <main id="main" class="main">

        @RenderBody()

    </main>
    <!-- End #main -->

    <!-- ======= Footer ======= -->
    <partial name="_FooterPartial"></partial>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    
    <partial name="_Js"></partial>

    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts",required:false);
</body>

</html>

WebShop/GearShop/Areas/Admin/Views/Shared/_Css.cshtml
<!-- Vendor CSS Files -->
<link href="~/Admin_assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Admin_assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
<link href="~/Admin_assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<link href="~/Admin_assets/vendor/quill/quill.snow.css" rel="stylesheet">
<link href="~/Admin_assets/vendor/quill/quill.bubble.css" rel="stylesheet">
<link href="~/Admin_assets/vendor/remixicon/remixicon.css" rel="stylesheet">
<link href="~/Admin_assets/vendor/simple-datatables/style.css" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="~/Admin_assets/css/style.css" rel="stylesheet">

<link href="~/admin_assets/css/paging.css" rel="stylesheet" />
@* plug-in datatable *@
<link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

WebShop/GearShop/Areas/Admin/Views/Shared/_CustomPaging.cshtml
<form hidden id="page-form" asp-action="Index" method="get">
    <input id="page-index" name="pageNumber" />
</form>

<script>
        $('#pagination').jqPaginator({
            totalPages: @Model.TotalPages,
            visiblePages: 3,
            currentPage: @Model.PageIndex,
            prev: '<li class="page-item"><a class="page-link" href="javascript:;">‹</a></li>',
            next: '<li class="page-item"><a class="page-link" href="javascript:;">›</a></li>',
            page: '<li class="page-item"><a class="page-link" href="javascript:;">{{page}}</a></li>',
            onPageChange: function (num) {
                if (this.currentPage != num) {
                    $('#page-index').val(num),
                        $('#page-form').submit()
                }
            }
        });
</script>

WebShop/GearShop/Areas/Admin/Views/Shared/_FooterPartial.cshtml
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Will</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
        Designed And Custom by <a href="https://www.facebook.com/le.pool.75/">Will</a>
    </div>
</footer><!-- End Footer -->

WebShop/GearShop/Areas/Admin/Views/Shared/_HeaderPartial.cshtml
 <!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
            <img src="~/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">Admin</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->


    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        You have 4 new notifications
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Lorem Ipsum</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>30 min. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-x-circle text-danger"></i>
                        <div>
                            <h4>Atque rerum nesciunt</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>1 hr. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-check-circle text-success"></i>
                        <div>
                            <h4>Sit rerum fuga</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>2 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-info-circle text-primary"></i>
                        <div>
                            <h4>Dicta reprehenderit</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>4 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Show all notifications</a>
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-chat-left-text"></i>
                    <span class="badge bg-success badge-number">3</span>
                </a><!-- End Messages Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                    <li class="dropdown-header">
                        You have 3 new messages
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="~/assets/img/messages-1.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>Maria Hudson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="~/assets/img/messages-2.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>Anna Nelson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>6 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="~/assets/img/messages-3.jpg" alt="" class="rounded-circle">
                            <div>
                                <h4>David Muldon</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>8 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="dropdown-footer">
                        <a href="#">Show all messages</a>
                    </li>

                </ul><!-- End Messages Dropdown Items -->

            </li><!-- End Messages Nav -->

            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>Kevin Anderson</h6>
                        <span>Web Designer</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                            <i class="bi bi-question-circle"></i>
                            <span>Need Help?</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

WebShop/GearShop/Areas/Admin/Views/Shared/_Js.cshtml
<!-- Vendor JS Files -->
<script src="~/Admin_assets/vendor/apexcharts/apexcharts.min.js"></script>
<script src="~/Admin_assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Admin_assets/vendor/chart.js/chart.umd.js"></script>
<script src="~/Admin_assets/vendor/echarts/echarts.min.js"></script>
<script src="~/Admin_assets/vendor/quill/quill.min.js"></script>
<script src="~/Admin_assets/vendor/simple-datatables/simple-datatables.js"></script>
<script src="~/Admin_assets/vendor/tinymce/tinymce.min.js"></script>
<script src="~/Admin_assets/vendor/php-email-form/validate.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<!-- Template Main JS File -->
<script src="~/Admin_assets/js/main.js"></script>
@* plug-in datatable *@
<script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
@* Sweet alert 2 *@
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@* Paging *@
<script src="~/js/jq-paginator.js"></script>

WebShop/GearShop/Areas/Admin/Views/Shared/_LeftSidebarPartial.cshtml
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Management</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a asp-controller="Product" asp-action="Index">
                        <i class="bi bi-circle"></i><span>Product </span>
                    </a>
                </li>
                <li>
                    <a asp-controller="Category" asp-action="Index">
                        <i class="bi bi-circle"></i><span>Category </span>
                    </a>
                </li>
                <li>
                    <a asp-controller="User" asp-action="Index">
                        <i class="bi bi-circle"></i><span>User</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Components Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>Profile</span>
            </a>
        </li><!-- End Profile Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" asp-area="Customer" asp-controller="Account" asp-action="Logout">
                <i class="ri-logout-circle-line"></i>
                <span>Log-Out</span>
            </a>
        </li><!-- End Login Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" asp-area="Customer" asp-controller="Home" asp-action="Index">
                <i class="bi bi-arrow-return-left"></i>
                <span>Go to home</span>
            </a>
        </li><!-- End Blank Page Nav -->

    </ul>

</aside><!-- End Sidebar-->